package ing.entity;
// Generated 19 mars 2016 16:26:07 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name = "groupe", catalog = "gestionabsence")
public class Groupe implements java.io.Serializable {

	private Long id;
	private String libelle;

	public Groupe() {
	}

	public Groupe(String libelle) {
		this.libelle = libelle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "libelle", length = 45)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

}
