package ing.entity;
// Generated 9 avr. 2016 22:00:36 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name = "matiere", catalog = "gestionabsence")
public class Matiere implements java.io.Serializable {

	private Long id;
	private String libelle;
	private Set<Absence> absences = new HashSet<Absence>(0);

	public Matiere() {
	}

	public Matiere(String libelle, Set<Absence> absences) {
		this.libelle = libelle;
		this.absences = absences;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "libelle", length = 45)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matiere")
	public Set<Absence> getAbsences() {
		return this.absences;
	}

	public void setAbsences(Set<Absence> absences) {
		this.absences = absences;
	}

}
