// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Annee generated by hbm2java
 */
public class Annee implements java.io.Serializable {

	private Long id;
	private Integer annee;
	private Date dateDeb;
	private Date dateFin;
	private Set etudiants = new HashSet(0);

	public Annee() {
	}

	public Annee(Integer annee, Date dateDeb, Date dateFin, Set etudiants) {
		this.annee = annee;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		this.etudiants = etudiants;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getAnnee() {
		return this.annee;
	}

	public void setAnnee(Integer annee) {
		this.annee = annee;
	}

	public Date getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(Date dateDeb) {
		this.dateDeb = dateDeb;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	public Set getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set etudiants) {
		this.etudiants = etudiants;
	}

}
