package com.projet.ing.entities;


// Generated 5 mars 2016 15:35:36 by Hibernate Tools 4.0.0

import java.util.Date;



import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Annee generated by hbm2java
 */
@Entity
public class Annee  {
@Id
@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	private Integer annee;
	private Date dateDeb;
	private Date dateFin;
	

	public Annee() {
	}

	public Annee(Integer annee, Date dateDeb, Date dateFin) {
		this.annee = annee;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getAnnee() {
		return this.annee;
	}

	public void setAnnee(Integer annee) {
		this.annee = annee;
	}

	public Date getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(Date dateDeb) {
		this.dateDeb = dateDeb;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}


}
