// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

/**
 * Comptes generated by hbm2java
 */
public class Comptes implements java.io.Serializable {

	private Long id;
	private String login;
	private String password;
	private String profile;

	public Comptes() {
	}

	public Comptes(String login, String password, String profile) {
		this.login = login;
		this.password = password;
		this.profile = profile;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

}
