// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

/**
 * Correspondance generated by hbm2java
 */
public class Correspondance implements java.io.Serializable {

	private CorrespondanceId id;
	private Enseignant enseignant;
	private Groupe groupe;
	private Matiere matiere;

	public Correspondance() {
	}

	public Correspondance(CorrespondanceId id, Enseignant enseignant, Groupe groupe, Matiere matiere) {
		this.id = id;
		this.enseignant = enseignant;
		this.groupe = groupe;
		this.matiere = matiere;
	}

	public CorrespondanceId getId() {
		return this.id;
	}

	public void setId(CorrespondanceId id) {
		this.id = id;
	}

	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

}
