// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Enseignant generated by hbm2java
 */
public class Enseignant implements java.io.Serializable {

	private Long id;
	private String nom;
	private String prenom;
	private Date datenaiss;
	private String adresse;
	private Set correspondances = new HashSet(0);

	public Enseignant() {
	}

	public Enseignant(String nom, String prenom, Date datenaiss, String adresse, Set correspondances) {
		this.nom = nom;
		this.prenom = prenom;
		this.datenaiss = datenaiss;
		this.adresse = adresse;
		this.correspondances = correspondances;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Date datenaiss) {
		this.datenaiss = datenaiss;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Set getCorrespondances() {
		return this.correspondances;
	}

	public void setCorrespondances(Set correspondances) {
		this.correspondances = correspondances;
	}

}
