// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant implements java.io.Serializable {

	private Long id;
	private Annee annee;
	private Groupe groupe;
	private String nom;
	private String prenom;
	private Date datenais;
	private String adresse;

	public Etudiant() {
	}

	public Etudiant(Annee annee, Groupe groupe) {
		this.annee = annee;
		this.groupe = groupe;
	}

	public Etudiant(Annee annee, Groupe groupe, String nom, String prenom, Date datenais, String adresse) {
		this.annee = annee;
		this.groupe = groupe;
		this.nom = nom;
		this.prenom = prenom;
		this.datenais = datenais;
		this.adresse = adresse;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Annee getAnnee() {
		return this.annee;
	}

	public void setAnnee(Annee annee) {
		this.annee = annee;
	}

	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDatenais() {
		return this.datenais;
	}

	public void setDatenais(Date datenais) {
		this.datenais = datenais;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

}
