// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Groupe generated by hbm2java
 */
public class Groupe implements java.io.Serializable {

	private Long id;
	private String niveau;
	private String filiere;
	private Set correspondances = new HashSet(0);
	private Set etudiants = new HashSet(0);

	public Groupe() {
	}

	public Groupe(String niveau, String filiere, Set correspondances, Set etudiants) {
		this.niveau = niveau;
		this.filiere = filiere;
		this.correspondances = correspondances;
		this.etudiants = etudiants;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	public String getFiliere() {
		return this.filiere;
	}

	public void setFiliere(String filiere) {
		this.filiere = filiere;
	}

	public Set getCorrespondances() {
		return this.correspondances;
	}

	public void setCorrespondances(Set correspondances) {
		this.correspondances = correspondances;
	}

	public Set getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set etudiants) {
		this.etudiants = etudiants;
	}

}
