// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Matiere generated by hbm2java
 */
public class Matiere implements java.io.Serializable {

	private Long id;
	private String nomMatiere;
	private Set correspondances = new HashSet(0);

	public Matiere() {
	}

	public Matiere(String nomMatiere, Set correspondances) {
		this.nomMatiere = nomMatiere;
		this.correspondances = correspondances;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNomMatiere() {
		return this.nomMatiere;
	}

	public void setNomMatiere(String nomMatiere) {
		this.nomMatiere = nomMatiere;
	}

	public Set getCorrespondances() {
		return this.correspondances;
	}

	public void setCorrespondances(Set correspondances) {
		this.correspondances = correspondances;
	}

}
