// default package
// Generated 29 févr. 2016 22:00:52 by Hibernate Tools 4.0.0

/**
 * Responsable generated by hbm2java
 */
public class Responsable implements java.io.Serializable {

	private long id;
	private String nom;
	private String prenom;
	private String adresse;
	private Integer cin;

	public Responsable() {
	}

	public Responsable(long id) {
		this.id = id;
	}

	public Responsable(long id, String nom, String prenom, String adresse, Integer cin) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.cin = cin;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Integer getCin() {
		return this.cin;
	}

	public void setCin(Integer cin) {
		this.cin = cin;
	}

}
