package rev;
// Generated 10 mars 2016 13:32:39 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Correspondance generated by hbm2java
 */
@Entity
@Table(name = "correspondance", catalog = "gestionabsense")
public class Correspondance implements java.io.Serializable {

	private CorrespondanceId id;

	public Correspondance() {
	}

	public Correspondance(CorrespondanceId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idGroupe", column = @Column(name = "id_groupe", nullable = false)),
			@AttributeOverride(name = "idEnseignant", column = @Column(name = "id_enseignant", nullable = false)),
			@AttributeOverride(name = "idMatiere", column = @Column(name = "id_matiere", nullable = false)) })
	public CorrespondanceId getId() {
		return this.id;
	}

	public void setId(CorrespondanceId id) {
		this.id = id;
	}

}
