package ing.entities;


// Generated 10 mars 2016 14:50:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Absence generated by hbm2java
 */
@Entity
@Table(name = "absence", catalog = "gestionabsense")
public class Absence implements java.io.Serializable {

	private long id;
	private Integer numeroSeance;
	private String date;
	private long idEtudiant;
	private long idMatiere;
	private long idEnseignant;

	public Absence() {
	}

	public Absence(long id, long idEtudiant, long idMatiere, long idEnseignant) {
		this.id = id;
		this.idEtudiant = idEtudiant;
		this.idMatiere = idMatiere;
		this.idEnseignant = idEnseignant;
	}

	public Absence(long id, Integer numeroSeance, String date, long idEtudiant, long idMatiere, long idEnseignant) {
		this.id = id;
		this.numeroSeance = numeroSeance;
		this.date = date;
		this.idEtudiant = idEtudiant;
		this.idMatiere = idMatiere;
		this.idEnseignant = idEnseignant;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "numero_seance")
	public Integer getNumeroSeance() {
		return this.numeroSeance;
	}

	public void setNumeroSeance(Integer numeroSeance) {
		this.numeroSeance = numeroSeance;
	}

	@Column(name = "date", length = 20)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "id_etudiant", nullable = false)
	public long getIdEtudiant() {
		return this.idEtudiant;
	}

	public void setIdEtudiant(long idEtudiant) {
		this.idEtudiant = idEtudiant;
	}

	@Column(name = "id_matiere", nullable = false)
	public long getIdMatiere() {
		return this.idMatiere;
	}

	public void setIdMatiere(long idMatiere) {
		this.idMatiere = idMatiere;
	}

	@Column(name = "id_enseignant", nullable = false)
	public long getIdEnseignant() {
		return this.idEnseignant;
	}

	public void setIdEnseignant(long idEnseignant) {
		this.idEnseignant = idEnseignant;
	}

}
