package ing.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Annee generated by hbm2java
 */
@Entity
@Table(name = "annee", catalog = "gestionabsense")
public class Annee implements java.io.Serializable {

	private Long id;
	private Integer annee;
	private String dateDeb;
	private String dateFin;
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

	public Annee() {
	}

	public Annee(Integer annee, String dateDeb, String dateFin, Set<Etudiant> etudiants) {
		this.annee = annee;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		this.etudiants = etudiants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "annee")
	public Integer getAnnee() {
		return this.annee;
	}

	public void setAnnee(Integer annee) {
		this.annee = annee;
	}

	@Column(name = "date_deb", length = 20)
	public String getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(String dateDeb) {
		this.dateDeb = dateDeb;
	}

	@Column(name = "date_fin", length = 20)
	public String getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(String dateFin) {
		this.dateFin = dateFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annee")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

}
