package ing.entities;


// Generated 5 mars 2016 15:35:36 by Hibernate Tools 4.0.0

import java.util.Date;



import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * Annee generated by hbm2java
 */
@Entity
@Table(name="annee")
public class Annee  {
@Id
@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	private Integer annee;
	private String dateDeb;
	private String dateFin;
	

	public Annee() {
	}

	public Annee(Integer annee, String dateDeb, String dateFin) {
		this.annee = annee;
		this.dateDeb = dateDeb;
		this.dateFin = dateFin;
		
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getAnnee() {
		return this.annee;
	}

	public void setAnnee(Integer annee) {
		this.annee = annee;
	}

	public String getDateDeb() {
		return this.dateDeb;
	}

	public void setDateDeb(String dateDeb) {
		this.dateDeb = dateDeb;
	}

	public String getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(String dateFin) {
		this.dateFin = dateFin;
	}


}
