package ing.entities;
// Generated 10 mars 2016 14:50:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CorrespondanceId generated by hbm2java
 */
@Embeddable
public class CorrespondanceId implements java.io.Serializable {

	private long idGroupe;
	private long idEnseignant;
	private long idMatiere;

	public CorrespondanceId() {
	}

	public CorrespondanceId(long idGroupe, long idEnseignant, long idMatiere) {
		this.idGroupe = idGroupe;
		this.idEnseignant = idEnseignant;
		this.idMatiere = idMatiere;
	}

	@Column(name = "id_groupe", nullable = false)
	public long getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(long idGroupe) {
		this.idGroupe = idGroupe;
	}

	@Column(name = "id_enseignant", nullable = false)
	public long getIdEnseignant() {
		return this.idEnseignant;
	}

	public void setIdEnseignant(long idEnseignant) {
		this.idEnseignant = idEnseignant;
	}

	@Column(name = "id_matiere", nullable = false)
	public long getIdMatiere() {
		return this.idMatiere;
	}

	public void setIdMatiere(long idMatiere) {
		this.idMatiere = idMatiere;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CorrespondanceId))
			return false;
		CorrespondanceId castOther = (CorrespondanceId) other;

		return (this.getIdGroupe() == castOther.getIdGroupe())
				&& (this.getIdEnseignant() == castOther.getIdEnseignant())
				&& (this.getIdMatiere() == castOther.getIdMatiere());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdGroupe();
		result = 37 * result + (int) this.getIdEnseignant();
		result = 37 * result + (int) this.getIdMatiere();
		return result;
	}

}
