package ing.entities;

import javax.persistence.Entity;

// Generated 5 mars 2016 15:35:36 by Hibernate Tools 4.0.0

/**
 * CorrespondanceId generated by hbm2java
 */
@Entity
public class CorrespondanceId {
 
	private long idGroupe;
	private long idEnseignant;
	private long idMatiere;

	public CorrespondanceId() {
	}

	public CorrespondanceId(long idGroupe, long idEnseignant, long idMatiere) {
		this.idGroupe = idGroupe;
		this.idEnseignant = idEnseignant;
		this.idMatiere = idMatiere;
	}

	public long getIdGroupe() {
		return this.idGroupe;
	}

	public void setIdGroupe(long idGroupe) {
		this.idGroupe = idGroupe;
	}

	public long getIdEnseignant() {
		return this.idEnseignant;
	}

	public void setIdEnseignant(long idEnseignant) {
		this.idEnseignant = idEnseignant;
	}

	public long getIdMatiere() {
		return this.idMatiere;
	}

	public void setIdMatiere(long idMatiere) {
		this.idMatiere = idMatiere;
	}

	

}
