package ing.entities;
// Generated 10 mars 2016 14:50:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "gestionabsense")
public class Etudiant implements java.io.Serializable {

	private Long id;
	private Annee annee;
	private Groupe groupe;
	private String nom;
	private String prenom;
	private Date datenais;
	private String adresse;
	private String login;
	private String password;

	public Etudiant() {
	}

	public Etudiant(Annee annee, Groupe groupe, String login, String password) {
		this.annee = annee;
		this.groupe = groupe;
		this.login = login;
		this.password = password;
	}

	public Etudiant(Annee annee, Groupe groupe, String nom, String prenom, Date datenais, String adresse, String login,
			String password) {
		this.annee = annee;
		this.groupe = groupe;
		this.nom = nom;
		this.prenom = prenom;
		this.datenais = datenais;
		this.adresse = adresse;
		this.login = login;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_annee", nullable = false)
	public Annee getAnnee() {
		return this.annee;
	}

	public void setAnnee(Annee annee) {
		this.annee = annee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_groupe", nullable = false)
	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 45)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datenais", length = 10)
	public Date getDatenais() {
		return this.datenais;
	}

	public void setDatenais(Date datenais) {
		this.datenais = datenais;
	}

	@Column(name = "adresse", length = 45)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "login", nullable = false, length = 45)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
