package ing.entities;


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Etudiant generated by hbm2java
 */
@Entity
public class Etudiant implements Serializable {
@Id
@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	
	private Annee annee;
	private Groupe groupe;
	private String nom;
	private String prenom;
	private Date datenais;
	private String adresse;
	private String login;
	private String password;

	public Etudiant() {
	}

	public Etudiant(Annee annee, Groupe groupe, String login, String password) {
		this.annee = annee;
		this.groupe = groupe;
		this.login = login;
		this.password = password;
	}

	public Etudiant(Absence absence, Annee annee, Groupe groupe, String nom, String prenom, Date datenais,
			String adresse, String login, String password) {
		
		this.annee = annee;
		this.groupe = groupe;
		this.nom = nom;
		this.prenom = prenom;
		this.datenais = datenais;
		this.adresse = adresse;
		this.login = login;
		this.password = password;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	

	public Annee getAnnee() {
		return this.annee;
	}

	public void setAnnee(Annee annee) {
		this.annee = annee;
	}

	public Groupe getGroupe() {
		return this.groupe;
	}

	public void setGroupe(Groupe groupe) {
		this.groupe = groupe;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDatenais() {
		return this.datenais;
	}

	public void setDatenais(Date datenais) {
		this.datenais = datenais;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
