package ing.entities;



import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Groupe generated by hbm2java
 */
@Entity
public class Groupe {
@Id
@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	private String niveau;
	private String filiere;
	

	public Groupe() {
	}

	public Groupe(String niveau, String filiere,Set<Etudiant> etudiants) {
		this.niveau = niveau;
		this.filiere = filiere;
		
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNiveau() {
		return this.niveau;
	}

	public void setNiveau(String niveau) {
		this.niveau = niveau;
	}

	public String getFiliere() {
		return this.filiere;
	}

	public void setFiliere(String filiere) {
		this.filiere = filiere;
	}

	
	

}
