package ing.entities;
// Generated 10 mars 2016 14:50:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Matiere generated by hbm2java
 */
@Entity
@Table(name = "matiere", catalog = "gestionabsense")
public class Matiere implements java.io.Serializable {

	private Long idMat;
	private String nomMatiere;

	public Matiere() {
	}

	public Matiere(String nomMatiere) {
		this.nomMatiere = nomMatiere;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_mat", unique = true, nullable = false)
	public Long getIdMat() {
		return this.idMat;
	}

	public void setIdMat(Long idMat) {
		this.idMat = idMat;
	}

	@Column(name = "nom_matiere", length = 45)
	public String getNomMatiere() {
		return this.nomMatiere;
	}

	public void setNomMatiere(String nomMatiere) {
		this.nomMatiere = nomMatiere;
	}

}
